### PR TITLE
implement projects page mvp

### PR DESCRIPTION
**Pull request by jay-joo-code**
image

image

### CODE REVIEW

**Review by A1pha0ps — CHANGES_REQUESTED** [review]
Just tested the web responsiveness. Could you add a bit more white space to the projects text? In the home page, there is a good amount of space on the left and right side of text. Was wondering if you could match that here too for consistency

**Comment by jay-joo-code** [comment]
> @jay-joo-code Could you make the web view slightly longer? On laptop I feel like you could fill the space up a bit more : ) mobile view is perfect though

do you mean longer as in wider horizontally?

**Comment by jay-joo-code** [comment]
image

@A1pha0ps made it wider!

**Review by A1pha0ps — APPROVED** [review]
looks good!

**Pull request merged**
